export const getAppliedJobsConstants = {
  GET_APPLIED_JOB_REQUEST: "GET_APPLIED_JOB_REQUEST ",
  GET_APPLIED_JOB_SUCCESS: "GET_APPLIED_JOB_SUCCESS",
  GET_APPLIED_JOB_FAILURE: "GET_APPLIED_JOB_FAILURE",
};
