export const getAppliedStudentsConstants = {
  GET_APPLIED_STUDENT_REQUEST: "GET_APPLIED_STUDENT_REQUEST ",
  GET_APPLIED_STUDENT_SUCCESS: "GET_APPLIED_STUDENT_SUCCESS",
  GET_APPLIED_STUDENT_FAILURE: "GET_APPLIED_STUDENT_FAILURE",
};
